# Generated by Django 4.2.17 on 2024-12-06 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearest_city', models.CharField()),
                ('status', models.CharField(choices=[('WR', 'Working'), ('TN', 'Temporarily not working'), ('CL', 'Closed')])),
                ('max_wingspan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airway',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('flight_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('surname', models.CharField(max_length=43)),
                ('middle_name', models.CharField(max_length=43)),
                ('e_mail', models.EmailField(max_length=254)),
                ('loyalty_program', models.CharField(choices=[('1', 'Low loyalty program'), ('2', 'High loyalty program')])),
                ('phone_num', models.CharField(validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_departure', models.DateField()),
                ('time_departure', models.TimeField()),
                ('date_arrival', models.DateField()),
                ('time_arrival', models.TimeField()),
                ('status', models.CharField(choices=[('CLD', 'Cancelled'), ('EXP', 'Expected'), ('DLD', 'Delayed'), ('IFL', 'In flight'), ('CTD', 'Completed')])),
            ],
        ),
        migrations.CreateModel(
            name='PassengerPlane',
            fields=[
                ('id_number', models.CharField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('load_capacity', models.IntegerField()),
                ('wingspan', models.IntegerField()),
                ('max_flight_range', models.IntegerField()),
                ('service_life', models.IntegerField()),
                ('status', models.CharField(choices=[('UR', 'Under repair'), ('ACT', 'Active')])),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('surname', models.CharField(max_length=43)),
                ('middle_name', models.CharField(max_length=43)),
                ('experience', models.IntegerField()),
                ('phone_num', models.CharField(validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRS', 'Priority service'), ('LS', 'Luggage service'), ('FFS', 'Additional meal'), ('ODF', 'Other services during flight'), ('OAF', 'Other services after flight')])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('surname', models.CharField(max_length=43)),
                ('middle_name', models.CharField(max_length=43)),
                ('phone_num', models.CharField(validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('position', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(null=True)),
                ('booking_status', models.CharField(choices=[('NO', 'Not booked'), ('YES', 'Booked')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviaCompanyApp.client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aviaCompanyApp.flight')),
                ('services', models.ManyToManyField(to='aviaCompanyApp.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='passengerplane',
            constraint=models.CheckConstraint(check=models.Q(('id_number__contains', '^[A-Z]{1,2}-[0-9]{5}$')), name='plane_number_constraint'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviaCompanyApp.airway'),
        ),
        migrations.AddField(
            model_name='airway',
            name='days_of_week',
            field=models.ManyToManyField(to='aviaCompanyApp.weekday'),
        ),
        migrations.AddField(
            model_name='airway',
            name='departure_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dep_Airport', to='aviaCompanyApp.airport'),
        ),
        migrations.AddField(
            model_name='airway',
            name='destination_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dest_Airport', to='aviaCompanyApp.airport'),
        ),
        migrations.AddField(
            model_name='airway',
            name='pilots',
            field=models.ManyToManyField(to='aviaCompanyApp.pilot'),
        ),
        migrations.AddField(
            model_name='airway',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviaCompanyApp.passengerplane'),
        ),
        migrations.AddField(
            model_name='airway',
            name='services',
            field=models.ManyToManyField(to='aviaCompanyApp.service'),
        ),
        migrations.AddField(
            model_name='airway',
            name='staff',
            field=models.ManyToManyField(to='aviaCompanyApp.staff'),
        ),
    ]
