# Generated by Django 5.1.4 on 2024-12-12 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearest_city', models.CharField()),
                ('international_code', models.CharField(validators=[django.core.validators.RegexValidator(regex='^[A-Z][A-Z][A-Z]$')])),
                ('status', models.CharField(choices=[('WR', 'Working'), ('TN', 'Temporarily not working'), ('CL', 'Closed')])),
                ('max_wingspan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('surname', models.CharField(max_length=43)),
                ('middle_name', models.CharField(max_length=43)),
                ('experience', models.IntegerField()),
                ('phone_num', models.CharField(validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LS', 'Luggage service'), ('FFS', 'Additional meal'), ('ODF', 'Other services during flight'), ('OAF', 'Other services after flight')])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=43)),
                ('surname', models.CharField(max_length=43)),
                ('middle_name', models.CharField(max_length=43)),
                ('phone_num', models.CharField(validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+?\\d{9,15}$')])),
                ('position', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=43, null=True)),
                ('surname', models.CharField(max_length=43, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(null=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex='^\\+?\\d{9,15}$')])),
                ('miles_balance', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airway',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('flight_duration', models.IntegerField()),
                ('departure_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dep_Airport', to='aviaCompanyApp.airport')),
                ('destination_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dest_Airport', to='aviaCompanyApp.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_departure', models.DateField()),
                ('time_departure', models.TimeField()),
                ('date_arrival', models.DateField()),
                ('time_arrival', models.TimeField()),
                ('status', models.CharField(choices=[('EXP', 'Expected'), ('CLD', 'Cancelled'), ('PLD', 'Planned'), ('DLD', 'Delayed'), ('IFL', 'In flight'), ('CTD', 'Completed')])),
                ('price', models.IntegerField()),
                ('airway', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aviaCompanyApp.airway')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerPlane',
            fields=[
                ('id_number', models.CharField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('load_capacity', models.IntegerField()),
                ('wingspan', models.IntegerField()),
                ('max_flight_range', models.IntegerField()),
                ('service_life', models.IntegerField()),
                ('status', models.CharField(choices=[('UR', 'Under repair'), ('ACT', 'Active')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id_number__contains', '^[A-Z]{1,2}-[0-9]{5}$')), name='plane_number_constraint')],
            },
        ),
        migrations.AddField(
            model_name='airway',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviaCompanyApp.passengerplane'),
        ),
        migrations.AddField(
            model_name='airway',
            name='pilots',
            field=models.ManyToManyField(to='aviaCompanyApp.pilot'),
        ),
        migrations.AddField(
            model_name='airway',
            name='services',
            field=models.ManyToManyField(to='aviaCompanyApp.service'),
        ),
        migrations.AddField(
            model_name='airway',
            name='staff',
            field=models.ManyToManyField(to='aviaCompanyApp.staff'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(null=True)),
                ('booking_status', models.CharField(choices=[('NO', 'Not booked'), ('YES', 'Booked')])),
                ('price', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aviaCompanyApp.flight')),
                ('services', models.ManyToManyField(to='aviaCompanyApp.service')),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], primary_key=True, serialize=False)),
                ('airway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviaCompanyApp.airway')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PSP', 'Паспорт'), ('IPS', 'Заграничный паспорт')])),
                ('custom_name', models.CharField(max_length=40)),
                ('number', models.CharField(validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('date_of_issue', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('number', 'type', 'date_of_issue')},
            },
        ),
    ]
