# Generated by Django 5.1.4 on 2024-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='loyalty_program',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('LS', 'Luggage service'), ('FFS', 'Additional meal'), ('ODF', 'Other services during flight'), ('OAF', 'Other services after flight')]),
        ),
    ]
