# Generated by Django 5.1.4 on 2024-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='type',
            field=models.CharField(choices=[('PSP', 'Паспорт'), ('BRT', 'Свидетельство о рождении'), ('IPS', 'Заграничный паспорт')]),
        ),
    ]
