# Generated by Django 5.1.4 on 2024-12-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doc',
            unique_together={('number', 'type', 'date_of_issue', 'custom_name')},
        ),
    ]
