# Generated by Django 5.1.4 on 2024-12-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0002_alter_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
