# Generated by Django 5.1.4 on 2025-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0002_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='exit_terminal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
