# Generated by Django 5.1.4 on 2024-12-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0002_alter_ticket_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='miles_balance',
        ),
    ]
