# Generated by Django 5.1.4 on 2025-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0003_flight_exit_terminal_flight_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('PLD', 'Ожидается регистрация'), ('EXP', 'Идет регистрация'), ('PRP', 'Посадка'), ('PRE', 'Посадка окончена'), ('IFL', 'В процессе'), ('CTD', 'Выполнен'), ('CLD', 'Отменен'), ('DLD', 'Задерживается')]),
        ),
    ]
