# Generated by Django 5.1.4 on 2025-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0004_alter_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='boarding_dtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='register_dtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
