# Generated by Django 5.1.4 on 2024-12-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0004_alter_ticket_client'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'document')},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aviaCompanyApp.cart'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'document'), ('flight', 'document', 'cart')},
        ),
    ]
