# Generated by Django 5.1.4 on 2025-01-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0005_flight_boarding_dtime_flight_register_dtime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flightseat',
            unique_together={('seat_num', 'flight', 'ticket_num')},
        ),
    ]
