# Generated by Django 5.1.4 on 2025-01-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaCompanyApp', '0006_alter_flightseat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
